name: condansis
channels:
  - conda-forge
  - defaults
dependencies:
  # required for CondaNSIS
  - jinja2
  - python>=3.8
  - conda-pack>=0.5
  - nsis
  # testing and docs
  - pytest
  - sphinx
  - numpydoc
  - wheel
  - pip
  - conda-lock
