
name: Test and Release


on:
  push:
    branches:
     - 'main'
     - 'feature/*'
     - 'hotfix/*'
    tags:
     - 'v*' 
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Test:
    runs-on: windows-latest
    if: ${{ startsWith(github.ref, 'refs/tags') }}

    steps:
      - uses: actions/checkout@v2

      - name: Create conda environment and run unit tests
        run: |
          call %CONDA%\Scripts\activate
          call conda env create -f environment.yml -n condansis
        shell: cmd
        
      - name: Install condansis and run test
        run: |
          call %CONDA%\Scripts\activate condansis
          call conda install pytest wheel
          python -m pip install .\src
          python -m pytest --junitxml=test-results.xml .\src
        shell: cmd
        
      - name: Run script example 
        run: |
          call %CONDA%\Scripts\activate condansis
          python example\script\create_installer.py
          start /wait "" install_snake-simulator-0.1.exe /S /D=%cd%\example_package_1
          example_package_1\snake.lnk
        shell: cmd
        
      - name: Run package example 
        run: |
          call %CONDA%\Scripts\activate condansis
          python example\package\create_installer.py
          start /wait "" install_snake-simulator-1.0.exe /S /D=%cd%\example_package_2
          example_package_2\snake.lnk
        shell: cmd
        
  Release:
    runs-on: ubuntu-latest
    #if: ${{ startsWith(github.ref, 'refs/tags') }}
      
    steps:
      - uses: actions/checkout@v2
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: condansis
          environment-file: environment.yml
      
      - name: Build and upload to PyPI
        run: |
          cd src
          conda info
          conda list
          conda activate condansis
          python -m pip install --upgrade setuptools wheel twine
          python setup.py bdist_wheel
          python setup.py sdist
          #python -m twine upload --repository testpypi dist/*.whl -u __token__ -p "$TOKEN"
        env:
          TOKEN: ${{ secrets.PYPI_TOKEN }}

      - name: Compile docs
        run: |
          cd docs
          conda activate condansis
          make html
          
      - name: Commit documentation changes
        run: |
          git clone https://"$TOKEN"@github.com/guilhermebs/CondaNSIS.git --branch gh-pages --single-branch gh-pages
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          git push
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
